# Generated by Django 2.1.8 on 2020-02-09 03:05

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default=students.models.increment_student_id, max_length=500, null=True, validators=[django.core.validators.RegexValidator(code='Number is invalide', message='Produce number must be Alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('first_name_en', models.CharField(max_length=255)),
                ('first_name_kh', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(max_length=255)),
                ('last_name_kh', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('1', 'M'), ('2', 'F')], max_length=20)),
                ('nationality_en', models.CharField(max_length=30)),
                ('nationality_kh', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to=students.models.user_directory_path, validators=[students.models.validate_file_extension])),
                ('certificate', models.FileField(blank=True, upload_to=students.models.user_directory_path, validators=[students.models.validate_file_extension])),
                ('description_en', models.TextField()),
                ('description_kh', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
