# Generated by Django 2.1.8 on 2020-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=20),
        ),
    ]
